version: '3.8'

services:
    auth_app:
        build: .
        env_file: .env
        container_name: auth_app
        ports:
            - "8000"
        volumes:
            - ./app/:/app
 
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        depends_on:
            - auth_app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
